config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"

  devise_for :users, path: 'admin', path_names: { 
  	sign_in: 'login'
  }

  devise_scope :user do
  	get 'admin', to: 'devise/sessions#new'
  end

  resources :dashboard, only: :index
  resources :doctors, only: [:index, :show]
  resources :pricing, only: [:index]
  
  namespace :dashboard do
    resources :doctors, only: [:index, :create, :show, :update]
    resources :blogs, only: :index
    resources :pricing, only: :index
  end

  namespace :categories do 
    resources :mental_health, only: :index
    resources :physical_health, only: :index
    resources :sexual_health, only: :index
  end

  get 'blog/:blog_name_slug', to: 'blogs#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :name, uniqueness: true  
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :specializations, dependent: :destroy
  has_one_attached :profile_picture

  validates :name, presence: true

  enum color: %i[orange red yellow]
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :pricing
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  has_many :points, dependent: :destroy

  enum ptype: %w[physical sexual mental lab]
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  belongs_to :doctor

  enum name: %w[sexual physical mental]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
          :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
  
  protect_from_forgery with: :null_session, if: proc { |c| c.request.format == "application/json" }
	
	prepend_before_action do
    locale = choose_locale
    locale = :en unless locale && locale.to_sym.in?(I18n.available_locales)

    I18n.locale = locale

    if params[:locale] && !cookies[:lang]
      cookies[:lang] = locale
    end
  end

	def choose_locale
    i18n_from_param = params[:locale]&.to_sym
    i18n_from_cookie = cookies[:lang]&.to_sym

    return i18n_from_param if i18n_from_param.in?(I18n.available_locales)
    return i18n_from_cookie if i18n_from_cookie.in?(I18n.available_locales)
    return http_accept_language.compatible_language_from(I18n.available_locales)
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_index_path
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index; end

  def show; end
end

app/controllers/categories/application_controller.rb
class Categories::ApplicationController < ApplicationController
  include WebpackerHelper
  
  layout 'categories'
end

app/controllers/categories/mental_health_controller.rb
class Categories::MentalHealthController < Categories::ApplicationController
  def index; end
end

app/controllers/categories/physical_health_controller.rb
class Categories::PhysicalHealthController < Categories::ApplicationController
  def index; end
end

app/controllers/categories/sexual_health_controller.rb
class Categories::SexualHealthController < Categories::ApplicationController
  def index; end
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_action :authenticate_user!

  layout "dashboard"
end

app/controllers/dashboard/blogs_controller.rb
class Dashboard::BlogsController < Dashboard::ApplicationController
  before_action :authenticate_user!

  def index; end

  def create
    Blog.create!(blogs_params)
  end

  private 

    def blogs_params
      params.permit(
        :title, 
        :content,
        :cover_image
      )
    end
end

app/controllers/dashboard/doctors_controller.rb
class Dashboard::DoctorsController < Dashboard::ApplicationController
  before_action :authenticate_user!
  helper_method :doctor

  def index; end

  def show; end
  
  def create
    doc = Doctor.create!(doctor_params) 
    # unless Doctor.all.where(name: doctor_params[:name]).any?
    redirect_to dashboard_doctor_path(doc)
  end

  def delete
    Doctor.find(doctor_params[:id]).destroy!
  end

  def update 
    doctor.update!(doctor_params)

    redirect_to dashboard_doctor_path(doctor)
  end

  private
    def doctor
      doctor ||= Doctor.find(params[:id])
    end

    def doctor_params 
      params.require(:doctor).permit(
        :name, 
        :booksy_url, 
        :lek_url, 
        :profile_picture, 
        :color,
        :description
      )
    end
end

app/controllers/dashboard/pricing_controller.rb
class Dashboard::PricingController < Dashboard::ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  helper_method :doctors, :doctor, :numbers_to_words

  def index; end

private
  
  def doctors
  	doctors ||= Doctor.preload(:specializations)
  end

  def doctor
  	doctor ||= Doctor.find(doctor_params[:id])
  end

  def doctor_params
  	params.permit(:id, :name, :booksy_url, :lek_url, :specialization)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController 
	def index; end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include WebpackerHelper
end

app/helpers/webpacker_helper.rb
module WebpackerHelper
  def page_pack_tags
    join_paths(application_pack_tags,
      controller_pack_tags)
  end

  def application_pack_tags
    join_paths(attempt_to_find(:stylesheet, 'application'),
      attempt_to_find(:javascript, 'application'))
  end

  def controller_pack_tags
    join_paths(attempt_to_find(:stylesheet, controller_pack_lookup),
      attempt_to_find(:javascript, controller_pack_lookup))
  end

  private
  
  def join_paths(*paths)
    paths.select(&:present?).join("\n\n").html_safe
  end
  
  def controller_pack_lookup
    @controller_pack_lookup ||= begin
      postfix = action_name.in?(%w[new create edit update]) ? "_form" : ""
      "#{controller_path}#{postfix}"
    end
  end
  
  def attempt_to_find(asset_type, asset_name)
    case asset_type.to_sym
    when :stylesheet then
      stylesheet_pack_tag(asset_name.to_s, media: :all)
    when :javascript then
      javascript_pack_tag(asset_name.to_s)
    else
      nil
    end
  rescue Webpacker::Manifest::MissingEntryError => e
    message = "Webpacker can't find file #{asset_name} of type #{asset_type}"
    logger.debug(message)
    nil
  end
end

app/views/categories/physical_health/index.slim
h1 abc

app/views/categories/sexual_health/index.slim
.header id="sexual-health-page"
  .container
    .row
      .col-md-5
        .heading
          h1.text-muted.text-orange = t('categories.sexual.title').upcase
          h2.sexual-health-heading = t('categories.sexual.heading').html_safe

          p.sexual-health-text Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris.
      .col-md-7
        p.text-center Image

  .section id="sexual-health-breaker"
    h2.text-center = t('categories.sexual.section_1').html_safe

    .row
      .col-md-4
        .category-card
      .col-md-4
        .category-card
      .col-md-4
        .category-card
      

app/views/dashboard/blogs/index.slim
h1 Blogs

app/views/dashboard/doctors/index.slim
h2.text-center = t("dashboard.doctors.all_doctors")

- Doctor.all.each_with_index do |d, i| 
  = i + 1
  | . 
  = link_to d.name, dashboard_doctor_path(d)
  br
hr

/ = form_with model: Doctor.new, url: dashboard_doctors_path, method: :post do |f|
/   = f.file_field :profile_picture

/   = f.label :name
/   = f.text_field :name
  
/   = f.label :booksy_url
/   = f.text_field :booksy_url

/   = f.label :lek_url
/   = f.text_field :lek_url

/   = f.submit

app/views/dashboard/doctors/show.slim
h2.doctor-name-title.text-center = doctor.name
hr

= form_with model: doctor, url: dashboard_doctor_path, method: :put do |f|
  .form-row
    .form-group.col-md-6
      = f.label :name, class: ' col-form-label'
      = f.text_field :name, class: 'form-control'
    .form-group.col-md-6
      - if doctor.profile_picture.attached?
        .text-center = image_tag doctor&.profile_picture&.variant(resize: '200x200')
    .form-group.col-md-12
      = f.label :description, class: ' col-form-label'
      = f.text_area :description, class: 'form-control'
    .form-group.col-md-6
      = f.label :booksy_url, class: "col-form-label"
      = f.text_field :booksy_url, class: 'form-control', placeholder: 'https://www.booksy.com/...'
    .form-group.col-md-6
      = f.label :lek_url, class: "col-form-label"
      = f.text_field :lek_url, class: 'form-control', placeholder: 'https://www.znanylekarz.pl/...'
    .form-group.col-md-6
      = f.label :profile_picture, class: "col-form-label" 
      br
      = f.file_field :profile_picture
    .form-group.col-md-6
      = f.label :color, class: "col-form-label" 
      br
      = f.select :color, Doctor.colors.keys.map { |w| [w.humanize, w] }, {}, class: "form-control"
    = f.submit 'Save', class: 'btn btn-primary form-control'

app/views/dashboard/index.slim
h1.text-center = t("dashboard.title")
hr

app/views/dashboard/pricing/index.slim
h1.text-center All Prices
hr

/ = form_with Pricing.physical.map, url: pricing_index_path, method: :put do |e|
/   .form-row
/     .col-md-6
/       p = t("pricing.physical.#{e.title}.title")
/     .col-md-6
/       = f.text_field :price
/     =f.submit "Save"

app/views/layouts/dashboard/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">SmartlifeClinic</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item active">
        <%= link_to('Doctors', dashboard_doctors_path, method: :get, class: "nav-link") %>
      </li>
      <li class="nav-item">
        <%= link_to('Pricing', dashboard_pricing_index_path, method: :get, class: "nav-link") %>

      </li>
  
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link text-danger") %>
        <% end %>
      </li>
    </ul>
    
  </div>
</nav>

app/views/pricing/index.slim
section style="overflow-x: hidden" id="pricing"
  .row
    .col-md-12.text-center
      h1 
        = t('pricing.title')
      p.pricing_text
        = t('pricing.reservation').html_safe
    .col-md-12
      ul.nav.justify-content-center.scroll role="tablist" id="pricing_tabs_nav"
        li.nav-item.pricing_box.active_tab
          a.nav-link id="physical-tab" data-toggle="tab" href="#physical_tab" role="tab" aria-controls="physical" aria-selected="true"
            = t('pricing.physical.button_text').upcase
        
        li.nav-item.pricing_box
          a.nav-link id="sexual-tab" data-toggle="tab" href="#sexual_tab" role="tab" aria-controls="sexual" aria-selected="true"
            = t('pricing.sexual.button_text').upcase
        
        li.nav-item.pricing_box
          a.nav-link id="psychological-tab" data-toggle="tab" href="#psychological" role="tab" aria-controls="psychological" aria-selected="true"
            = t('pricing.psychologic.button_text').upcase
        
        li.nav-item.pricing_box
          a.nav-link id="lab-tab" data-toggle="tab" href="#lab" role="tab" aria-controls="lab" aria-selected="true"
            = t('pricing.lab.button_text').upcase
      
      .container.pricing_tabs
        .tab-content id="myTabContent"
          .tab-pane.fade.show.active id="physical_tab" role="tabpanel"aria-labelledby="physical-tab"
            = render 'pricing/layouts/physical_tab'

          .tab-pane.fade id="psychological" role="tabpanel" aria-labelledby="psychological-tab"
            = render 'pricing/layouts/psychological_tab'

          .tab-pane.fade id="sexual_tab" role="tabpanel" aria-labelledby="sexual-tab"
            = render 'pricing/layouts/sexual_tab'

          .tab-pane.fade id="lab" role="tabpanel" aria-labelledby="lab-tab"
            = render 'pricing/layouts/lab_tab'

javascript:
  var btns = document.getElementsByClassName("pricing_box");
  console.log(btns);
  for (var i = 0; i < btns.length; i++) {
    btns[i].addEventListener("click", function() {
    var current = document.getElementsByClassName("active_tab");
    if (current.length > 0) { 
      current[0].className = current[0].className.replace("active_tab", "");
    }
    this.className += " active_tab";
    });
  }