config/routes.rb
Rails.application.routes.draw do
  root "homepage#index"

  devise_for :users, path: 'admin', path_names: { 
  	sign_in: 'login'
  }

  devise_scope :user do
  	get 'admin', to: 'devise/sessions#new'
  end

  resources :dashboard, only: :index
  resources :doctors, only: [:index, :show]
  resources :pricing, only: [:index]
  
  namespace :dashboard do
    resources :doctors, only: [:index, :create, :show, :update]
    resources :blogs, only: :index
    resources :pricing, only: :index
  end

  namespace :categories do 
    resources :mental_health, only: :index
    resources :physical_health, only: :index
    resources :sexual_health, only: :index
  end

  get 'blog/:blog_name_slug', to: 'blogs#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :name, uniqueness: true  
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_many :specializations, dependent: :destroy
  has_one_attached :profile_picture

  validates :name, presence: true

  enum color: %i[orange red yellow]
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :pricing
end

app/models/pricing.rb
class Pricing < ApplicationRecord
  has_many :points, dependent: :destroy

  enum ptype: %w[physical sexual mental lab]
end

app/models/specialization.rb
class Specialization < ApplicationRecord
  belongs_to :doctor

  enum name: %w[sexual physical mental]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
          :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ApplicationHelper
  
  protect_from_forgery with: :null_session, if: proc { |c| c.request.format == "application/json" }
	
	prepend_before_action do
    locale = choose_locale
    locale = :en unless locale && locale.to_sym.in?(I18n.available_locales)

    I18n.locale = locale

    if params[:locale] && !cookies[:lang]
      cookies[:lang] = locale
    end
  end

	def choose_locale
    i18n_from_param = params[:locale]&.to_sym
    i18n_from_cookie = cookies[:lang]&.to_sym

    return i18n_from_param if i18n_from_param.in?(I18n.available_locales)
    return i18n_from_cookie if i18n_from_cookie.in?(I18n.available_locales)
    return http_accept_language.compatible_language_from(I18n.available_locales)
  end

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || dashboard_index_path
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

  def index; end

  def show; end
end

app/controllers/categories/application_controller.rb
class Categories::ApplicationController < ApplicationController
  include WebpackerHelper
  
  layout 'categories'
end

app/controllers/dashboard/application_controller.rb
class Dashboard::ApplicationController < ApplicationController
  before_action :authenticate_user!

  layout "dashboard"
end

app/controllers/dashboard/blogs_controller.rb
class Dashboard::BlogsController < Dashboard::ApplicationController
  before_action :authenticate_user!

  def index; end

  def create
    Blog.create!(blogs_params)
  end

  private 

    def blogs_params
      params.permit(
        :title, 
        :content,
        :cover_image
      )
    end
end

app/controllers/dashboard/doctors_controller.rb
class Dashboard::DoctorsController < Dashboard::ApplicationController
  before_action :authenticate_user!
  helper_method :doctor

  def index; end

  def show; end
  
  def create
    doc = Doctor.create!(doctor_params) 
    # unless Doctor.all.where(name: doctor_params[:name]).any?
    redirect_to dashboard_doctor_path(doc)
  end

  def delete
    Doctor.find(doctor_params[:id]).destroy!
  end

  def update 
    doctor.update!(doctor_params)

    redirect_to dashboard_doctor_path(doctor)
  end

  private
    def doctor
      doctor ||= Doctor.find(params[:id])
    end

    def doctor_params 
      params.require(:doctor).permit(
        :name, 
        :booksy_url, 
        :lek_url, 
        :profile_picture, 
        :color,
        :description
      )
    end
end

app/controllers/dashboard/pricing_controller.rb
class Dashboard::PricingController < Dashboard::ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  helper_method :doctors, :doctor, :numbers_to_words

  def index; end

private
  
  def doctors
  	doctors ||= Doctor.preload(:specializations)
  end

  def doctor
  	doctor ||= Doctor.find(doctor_params[:id])
  end

  def doctor_params
  	params.permit(:id, :name, :booksy_url, :lek_url, :specialization)
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController 
	def index; end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include WebpackerHelper
end

app/helpers/webpacker_helper.rb
module WebpackerHelper
  def page_pack_tags
    join_paths(application_pack_tags,
      controller_pack_tags)
  end

  def application_pack_tags
    join_paths(attempt_to_find(:stylesheet, 'application'),
      attempt_to_find(:javascript, 'application'))
  end

  def controller_pack_tags
    join_paths(attempt_to_find(:stylesheet, controller_pack_lookup),
      attempt_to_find(:javascript, controller_pack_lookup))
  end

  private
  
  def join_paths(*paths)
    paths.select(&:present?).join("\n\n").html_safe
  end
  
  def controller_pack_lookup
    @controller_pack_lookup ||= begin
      postfix = action_name.in?(%w[new create edit update]) ? "_form" : ""
      "#{controller_path}#{postfix}"
    end
  end
  
  def attempt_to_find(asset_type, asset_name)
    case asset_type.to_sym
    when :stylesheet then
      stylesheet_pack_tag(asset_name.to_s, media: :all)
    when :javascript then
      javascript_pack_tag(asset_name.to_s)
    else
      nil
    end
  rescue Webpacker::Manifest::MissingEntryError => e
    message = "Webpacker can't find file #{asset_name} of type #{asset_type}"
    logger.debug(message)
    nil
  end
end

app/views/layouts/_footer.slim
footer
  .row
    .col-lg-5.text-center
      .embed-responsive.embed-responsive-4by3
        iframe.embed-responsive-item src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2444.317942933431!2d20.98555141599367!3d52.21944116621176!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x471ecdbc1f5b8287%3A0x8d1e36ad170974b5!2sSmart%20Life%20Clinic!5e0!3m2!1sen!2sin!4v1577910020484!5m2!1sen!2sin" width="561" height="438" frameborder="0" style="border:0;" allowfullscreen="true" SameSite="None"
    .col-sm-12.col-lg-7
      span.text-center
        = image_tag('logo.svg', id: "footer-logo", class: "img-fluid m-left10") 

      .row.m-left10
        .col-sm-6.footer-points
          h4 
            = t('footer.address')
          p.footer-text 
            | ul. Marszałkowska 26/25 
            br
            | 150-520 Warszawa 
            
            br
            br
            | Wejście od tyłu budynku
          
        .col-sm-6.footer-points.pull-left
          h4 
            = t('footer.contact')
          p.footer-text
            a href="mailto:info@smartlifeclinic.pl"
            | info@smartlifeclinic.pl
            br
            | Recepcja: 
            a href="tel:+48506166303"
        .col-sm-6.footer-points
          h4 
            = t('footer.timing') 
          p.footer-text
            | pn-pt: 17:00 - 21:30 
            br
            | sb-nd: 11:00 - 16:00 
            br 
            br
            | Możliwe wizyty indywidualne 
            br
            | w dodatkowych godzinach.
        .col-sm-6.footer-points
          h4 Social media icons

app/views/layouts/_navbar.slim
nav.navbar.navbar-expand-lg.navbar-light
  .container-fluid
    a.navbar-brand href="/"
      = image_tag('logo.svg', id: "logo", width: "230", height: "35", alt: "smartlife clinic")
    button.navbar-toggler type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
      span.navbar-toggler-icon

    .collapse.navbar-collapse id="navbarSupportedContent"
      ul.navbar-nav.ml-auto
        li.nav-item
          = link_to t('navbar.sex_health'), categories_sexual_health_index_path, class: 'nav-link'

        li.nav-item
          = link_to t('navbar.mental_health'), categories_mental_health_index_path, class: 'nav-link'

        li.nav-item
          = link_to t('navbar.physical_health'), categories_physical_health_index_path, class: 'nav-link'

        li.nav-item
          = link_to t('navbar.specialists'), doctors_path, class: 'nav-link'

        li.nav-item
          = link_to t('navbar.pricing'), pricing_index_path, class: 'nav-link'

        li
          .my-2.my-lg-0
            = button_to t('navbar.book_now'), "https://booksy.com/pl-pl/6969_smart-life-clinic-kubicka-krapiec_zdrowie_3_warszawa", class: "btn btn-brown my-2 my-sm-0", type: 'submit'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Life Clinic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'animations', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
    
    <%= javascript_pack_tag 'scroll_magic', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'typed_animations', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/layouts/categories.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Life Clinic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= controller_pack_tags %>
    
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <%= yield %>
    
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Smart Life Clinic</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'dashboard/styles', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>

  <body>
    <div class="container">
      <%= render 'layouts/dashboard/navbar' %>
      
      <%= yield %>
    </div>
  </body>
</html>